### ISSUE TITLE
Can't get tutorial example to work

### ISSUE THREAD

**Issue by sjanko2** [opensistemas-hub/osbrain#144]
Hello,

I am new to working with osbrain and am trying to follow along with the documentation.

I have set up osbrain in a virtual environment using Python 3.6.1, and am using PyCharm Community Edition 2017.1

**I have copied and pasted the example code found here:** http://osbrain.readthedocs.io/en/stable/basic_patterns.html

---

```
import time
from osbrain import run_agent
from osbrain import run_nameserver

def log_message(agent, message):
    agent.log_info('Received: %s' % message)

if __name__ == '__main__':

    # System deployment
    run_nameserver()
    alice = run_agent('Alice')
    bob = run_agent('Bob')

    # System configuration
    addr = alice.bind('PUSH', alias='main')
    bob.connect(addr, handler=log_message)

    # Send messages
    while True:
        time.sleep(1)
        alice.send('main', 'Hello, Bob!')
```

---

**When I run this, I get a very long list of errors that appears to be about the execution of 'bind'. I'm uncertain what to do about it and have tried searching online...all I could find was information about different versions of zmq and how difficult it is using it on Windows. Any suggestions you can offer would be wonderful, thank you!**

**Sam**

```
C:\Users\Samantha\Anaconda\envs\bunnies\python.exe C:/Users/Samantha/Documents/Pycharm/PracticewithOSBrain/OSbraintutorials.py
Broadcast server running on 0.0.0.0:9091
NS running on 127.0.0.1:18492 (127.0.0.1)
URI = PYRO:Pyro.NameServer@127.0.0.1:18492
----------------------------------------------------
ERROR [2017-06-20 02:08:40.503039] (Alice): An exception occured while running! (Protocol not supported)
 EXCEPTION <class 'zmq.error.ZMQError'>: Error executing `bind`! (Protocol not supported)


> method: bind
|>>>>>>>>Traceback (most recent call last):
> args: ('PUSH',)
> kwargs: {'alias': 'main'}

|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1430, in run
|>>>>>>>>Traceback (most recent call last):
|     self.loop()
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 259, in _handle_loopback_safe
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1007, in loop
|     response = getattr(self, method)(*args, **kwargs)
|     if self.iterate():
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 607, in bind
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1041, in iterate
|     serializer)
|     self._process_events(events)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 639, in _bind_address
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1078, in _process_events
|     addr = self._bind_socket(socket, addr=addr, transport=transport)
|     self._process_single_event(socket)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 732, in _bind_socket
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1096, in _process_single_event
|     socket.bind('%s://%s' % (transport, addr))
|     self._process_rep_event(socket, address, data)
|   File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5653)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1138, in _process_rep_event
|   File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
|     execute_code_after_yield(generator)
| zmq.error.ZMQError: Protocol not supported
|<<<<<<<<
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 144, in execute_code_after_yield
 Extended stacktrace follows (most recent call last)
|     next(generator)
----------------------------------------------------
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 259, in _handle_loopback_safe
File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\proxy.py", line 159, in Proxy._pyroInvoke
|     response = getattr(self, method)(*args, **kwargs)
Source code:
    methodname, args, kwargs, flags, objectId)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 607, in bind
----------------------------------------------------
|     serializer)
File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\proxy.py", line 206, in Proxy._remote_call
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 639, in _bind_address
Source code:
    raise result
|     addr = self._bind_socket(socket, addr=addr, transport=transport)
Local values:
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 732, in _bind_socket
    __class__ = <class 'osbrain.proxy.Proxy'>
|     socket.bind('%s://%s' % (transport, addr))
    args = ('PUSH',)
    flags = 0
    kwargs = {'alias': 'main'}
|   File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5653)
    methodname = 'bind'
    objectId = None
|   File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
    result = ZMQError('Error executing `bind`! (Protocol not supported)

| zmq.error.ZMQError: Protocol not supported
> method: bind
|<<<<<<<<
> args: ('PUSH',)
Exception in thread oneway-call:
> kwargs: {'alias': 'main'}

Traceback (most recent call last):
|>>>>>>>>Traceback (most recent call last):
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 259, in _handle_loopback_safe
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\Pyro4\core.py", line 1784, in run
|     response = getattr(self, method)(*args, **kwargs)
    super(_OnewayCallThread, self).run()
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 607, in bind
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\threading.py", line 864, in run
|     serializer)
    self._target(*self._args, **self._kwargs)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 639, in _bind_address
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1430, in run
    self.loop()
|     addr = self._bind_socket(socket, addr=addr, transport=transport)
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1007, in loop
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 732, in _bind_socket
    if self.iterate():
|     socket.bind('%s://%s' % (transport, addr))
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1041, in iterate
|   File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5653)
    self._process_events(events)
|   File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1078, in _process_events
| zmq.error.ZMQError: Protocol not supported
    self._process_single_event(socket)
|<<<<<<<<')
    safe_args = ['bind', 'PUSH']
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1096, in _process_single_event
    self = <osbrain.proxy.Proxy at 0x3e75790; connected IPv4; for PYRONAME:Alice@127.0.0.1:18492>
    self._process_rep_event(socket, address, data)
        self._pyroUri = <Pyro4.core.URI at 0x3e75750; PYRONAME:Alice@127.0.0.1:18492>
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 1138, in _process_rep_event
        self._pyroConnection = <Pyro4.socketutil.SocketConnection object at 0x03E821E8>
    execute_code_after_yield(generator)
        self._pyroSerializer = None
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 144, in execute_code_after_yield
    next(generator)
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 259, in _handle_loopback_safe
    response = getattr(self, method)(*args, **kwargs)
        self._pyroMethods = {'set_logger', 'iterate', 'list_timers', 'registered', 'set_method', 'run', 'stop_all_timers', 'register', 'loop', 'subscribe', 'execute_function', 'after', 'safe_call', 'log_warning', 'bind', 'get_unique_external_zmq_sockets', 'log_info', 'addr', 'recv', 'each', 'raise_exception', 'log_error', 'iddle', 'set_attr', 'kill', 'on_init', 'connect', 'send', 'ping', 'log_debug', 'close_sockets', 'stop_timer', 'send_recv', 'get_attr', 'stop', 'shutdown'}
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 607, in bind
        self._pyroAttrs = set()
    serializer)
        self._pyroOneway = {'run'}
        self._pyroSeq = 4
        self._pyroRawWireResponse = False
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 639, in _bind_address
        self._pyroHandshake = 'hello'
    addr = self._bind_socket(socket, addr=addr, transport=transport)
        self._pyroMaxRetries = 0
        self._Proxy__pyroHmacKey = None
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 732, in _bind_socket
        self._Proxy__pyroTimeout = 0.0
    socket.bind('%s://%s' % (transport, addr))
        self._Proxy__pyroConnLock = <unlocked _thread.RLock object owner=0 count=0 at 0x03C36B48>
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5653)
        self._Proxy__async = False
        self._default_safe = True
        self._safe = True
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
        self._next_oneway = False
zmq.error.ZMQError: Protocol not supported
----------------------------------------------------
 EXCEPTION <class 'zmq.error.ZMQError'>: Error executing `bind`! (Protocol not supported)

> method: bind
> args: ('PUSH',)
> kwargs: {'alias': 'main'}

|>>>>>>>>Traceback (most recent call last):
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 259, in _handle_loopback_safe
|     response = getattr(self, method)(*args, **kwargs)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 607, in bind
|     serializer)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 639, in _bind_address

|     addr = self._bind_socket(socket, addr=addr, transport=transport)
Traceback (most recent call last):
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 732, in _bind_socket
  File "C:/Users/Samantha/Documents/Pycharm/PracticewithOSBrain/OSbraintutorials.py", line 16, in <module>
|     socket.bind('%s://%s' % (transport, addr))
|   File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5653)
|   File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
| zmq.error.ZMQError: Protocol not supported
|<<<<<<<<
----------------------------------------------------
    addr = alice.bind('PUSH', alias='main')
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\Pyro4\core.py", line 186, in __call__
    return self.__send(self.__name, args, kwargs)
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\proxy.py", line 159, in _pyroInvoke
    methodname, args, kwargs, flags, objectId)
  File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\proxy.py", line 206, in _remote_call
    raise result
zmq.error.ZMQError: Error executing `bind`! (Protocol not supported)

> method: bind
> args: ('PUSH',)
> kwargs: {'alias': 'main'}

|>>>>>>>>Traceback (most recent call last):
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 259, in _handle_loopback_safe
|     response = getattr(self, method)(*args, **kwargs)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 607, in bind
|     serializer)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 639, in _bind_address
|     addr = self._bind_socket(socket, addr=addr, transport=transport)
|   File "C:\Users\Samantha\Anaconda\envs\bunnies\lib\site-packages\osbrain\agent.py", line 732, in _bind_socket
|     socket.bind('%s://%s' % (transport, addr))
|   File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq\backend\cython\socket.c:5653)
|   File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
| zmq.error.ZMQError: Protocol not supported
|<<<<<<<<
```

**Comment by Peque** [comment]
@sjanko2 You are probably using Windows, am I right? If so, try to change the default transport protocol to TCP:

```python
osbrain.config['TRANSPORT'] = 'tcp'
```

Like so:

```python
import time

import osbrain
from osbrain import run_agent
from osbrain import run_nameserver


osbrain.config['TRANSPORT'] = 'tcp'


def log_message(agent, message):
    agent.log_info('Received: %s' % message)


if __name__ == '__main__':

    # System deployment
    run_nameserver()
    alice = run_agent('Alice')
    bob = run_agent('Bob')

    # System configuration
    addr = alice.bind('PUSH', alias='main')
    bob.connect(addr, handler=log_message)

    # Send messages
    while True:
        time.sleep(1)
        alice.send('main', 'Hello, Bob!')
```

We will include a better default for Windows in the next release.

**Comment by Peque** [comment]
Related: #146, #147.

**Comment by Peque** [comment]
@sjanko2 It will take some time for us to setup AppVeyor CI for Windows and we will not merge any fix until we setup the CI. So, for now, I suggest you to go with the workaround I proposed above (simply change the default transport on your scripts).

Thanks for reporting this issue. :blush:

**Comment by sjanko2** [comment]
This worked great, thank you so much!
